# Data Analytics 3

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('https://raw.githubusercontent.com/mk-gurucharan/Classification/master/IrisDataset.csv')
X = dataset.iloc[:,:4].values
y = dataset['species'].values
dataset.head(5)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [5]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [6]:
y_pred = classifier.predict(X_test) 
y_pred

array(['versicolor', 'virginica', 'virginica', 'virginica', 'virginica',
       'setosa', 'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'virginica', 'versicolor', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'virginica', 'versicolor', 'virginica', 'virginica', 'setosa',
       'virginica', 'versicolor', 'setosa', 'setosa', 'setosa'],
      dtype='<U10')

In [7]:
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Real Values Predicted Values
0   versicolor       versicolor
1    virginica        virginica
2    virginica        virginica
3    virginica        virginica
4    virginica        virginica
5       setosa           setosa
6   versicolor       versicolor
7    virginica       versicolor
8    virginica       versicolor
9   versicolor       versicolor
10   virginica        virginica
11  versicolor       versicolor
12   virginica        virginica
13  versicolor       versicolor
14  versicolor       versicolor
15      setosa           setosa
16      setosa           setosa
17  versicolor       versicolor
18  versicolor       versicolor
19  versicolor       versicolor
20   virginica        virginica
21  versicolor       versicolor
22   virginica        virginica
23   virginica        virginica
24      setosa           setosa
25   virginica        virginica
26  versicolor       versicolor
27      setosa           setosa
28      setosa           setosa
29      setosa           setosa

In [8]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print('Confusion matrix\n\n', cm)

print('\nTrue Positives(TP) = ', cm[0,0])

print('\nTrue Negatives(TN) = ', cm[1,1])

print('\nFalse Positives(FP) = ', cm[0,1])

print('\nFalse Negatives(FN) = ', cm[1,0])

print('\nAccuracy =',((cm[0,0]+cm[1,1])/(cm[0,1]+cm[1,0]+cm[0,0]+cm[1,1])))

Confusion matrix

 [[ 7  0  0]
 [ 0 11  0]
 [ 0  2 10]]

True Positives(TP) =  7

True Negatives(TN) =  11

False Positives(FP) =  0

False Negatives(FN) =  0

Accuracy = 1.0


In [9]:
#Accuracy = (TP+TN)/(TP+TN+FP+FN))
#Precision = TP/(TP+FP))
#Recall = TP/(TP+FN))

print("The Accuracy is ", (cm[0,0]+cm[1,1])/(cm[0,0]+cm[1,1]+cm[0,1]+cm[1,0]))
print("The precision is ", cm[0,0]/(cm[0,0]+cm[0,1]))
print("The recall is ", cm[0,0]/(cm[0,0]+cm[1,0]))

The Accuracy is  1.0
The precision is  1.0
The recall is  1.0
